/**
 * @description       :
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-16-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class ogrenci11 {
    public ogrenci11(){
        System.debug('yeni bir kayit yapildi');
    }
    public string firstName;
    public string lastName;
    private string schoolName='Dream School';
    public string className;
    public string language;
    public boolean art;
    public boolean sport;
    public integer ingGrade;
    public integer mathGrade;
    public integer fenGrade;
}