/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-16-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class ParametreliMetotlar11 {
    //Bu metot paremetre olarak string bir değer alsın. Bu stringin karakter sayısını return etsin.
    public integer uzunluk(string text) {
        integer uzn = text.length();
        return uzn;
    }
}